---

- hosts: all
  pre_tasks:
   
   - name: install updates (Rocky)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "Rocky"

   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  tasks:
 
  - name: install apache and php for Rocky Linux servers
    tags: apache,rocky,httpd
    dnf:
      name:
         - httpd
         - php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  tasks:
  
  - name: install mariabdb package (Rocky)
    tags: mariadb,rocky,db
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install mariadb package (Ubuntu)
    tags: mariab,ubuntu,db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
