---

- hosts: all
  pre_tasks:
   
   - name: install updates (Rocky)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "Rocky"

   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"


- hosts: workstations
  tasks:
  
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
     src: https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
     dest: /usr/local/bin
     remote_src: yes
     mode: 0755
     owner: root
     group: root

- hosts: web_servers
  tasks:
 
  - name: install apache and php for Rocky Linux servers
    tags: apache,rocky,httpd
    dnf:
      name:
         - httpd
         - php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for test site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  tasks:
  
  - name: install mariabdb package (Rocky)
    tags: mariadb,rocky,db
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install mariadb package (Ubuntu)
    tags: mariab,ubuntu,db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
